[package]
name = "geomy"
version = "0.1.2"
description = "A 3D mesh toolbox"
authors = ["geomy contributors"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
